### ISSUE TITLE
GPL-3.0 Licence

### ISSUE THREAD

**Issue by nineteendo** [LolHacksRule/GameFileFormatsRE#2]
General Format Info:
... https://github.com/Nineteendo/PVZ2tools/blob/183078174f3bda15bd06f7fefd0cbf4ebb8bf4e8/OBBEdit/README.md

Have you used this as a source for PopCapResourceStreamBin.bt? Because then you need to include this license as well:
https://github.com/Nineteendo/PVZ2tools/blob/master/LICENSE
If you don't want to do this you must remove the documentation based upon my research.

Thanks for the understanding.

**Comment by LolHacksRule** [comment]
I have added the GPL license, thanks for the request.

**Comment by nineteendo** [comment]
Ok, thank you for fixing the issue.
