### ISSUE TITLE
Tool for CFW2

### ISSUE THREAD

**Issue by ThePrimalPea** [LolHacksRule/GameFileFormatsRE#3]
Hi there, i want to ask if there's any tool can generate bitmap font and CFW2 file? It's for PvZ Free (rsb)

**Comment by LolHacksRule** [comment]
Hello there,

There's currently no tools to do that available aside from Font Builder from the public framework which is severely outdated and doesn't write the binary font format. I'm pretty sure Twist and beyond (not PVZ) can generate it from a source text file on it's own (if you have one) in case you really want to make a modified binary file, but that shouldn't be required as compiled wide/unicode fonts are only used for load optimization.

**Comment by LolHacksRule** [comment]
Well speak of the devil, this can decode and encode the binary widefont https://github.com/twinkles-twinstar/TwinStar.ToolKit

**Comment by ThePrimalPea** [comment]
What, which function

**Comment by LolHacksRule** [comment]
You mean what to enter after passing the binary file to it? 65 should decode it.

**Comment by ThePrimalPea** [comment]
Oh, i used it. That function can encode and decode CFW2 file. But the thing i need here is how to generate that file along with the atlas.

**Comment by LolHacksRule** [comment]
At the moment, that has to be done seperately.
