### ISSUE TITLE
Support for RSB version 1

### ISSUE THREAD

**Issue by twinstar6980** [LolHacksRule/GameFileFormatsRE#5]
I wish bt script would support rsb version 1.
I have analyzed this version RSB and here are the differences from version 3:
1. The first uint32 after the rsb version number is 1, while 3 and 4 are 0
2. There are only idx and ratio data in SubGroupInfo, there is no lang, and lang does not exist in the XML segment (so, the size of the group segment is 0x284 instead of 0x484)
3. The last two uint32s (texCnt and idx) do not exist in the ResGroupInfo segment. In this version, these two values are taken from the last two uint32s of the pool segment

btw, I noticed some incorrect naming in this script, you can check this file to understand the structure of rsb and rsg (including versions 1, 3, 4 and extensions of pvz2c): [structure.hpp](https://github.com/twinkles-twinstar/TwinStar.ToolKit/blob/master/Core/core/tool/popcap/resource_stream_bundle/structure.hpp).

**Comment by LolHacksRule** [comment]
Hello there, in regards to this format, I've been looking at Bejeweled Classic v1.0.0 as well as Candy Train and other obscure iOS exclusive PopCap titles (aside from Solitaire Blitz) which also use RSB V1 but anyway thanks for the legacy format suggestions. Today I'll probably update it.

Edit: Candy train does not use RSB in any form

**Comment by twinstar6980** [comment]
Candy Train? it use RSB v1 ? can you share the ipa of this game ? 
Also, regarding the ppf file, do you know its structure?
BTW, I also analyzed three versions of popfx, they are used in Bejeweled classic 1.0, 1.1 and pvz2, this is my decoding implementation: [src](https://github.com/twinkles-twinstar/TwinStar.ToolKit/blob/master/Core/core/tool/popcap/effect/encode.hpp), do you know any other popcap games that use popfx?

**Comment by LolHacksRule** [comment]
I haven't looked too much at PPF, POPFX is also used in PVZ1 (Mobile), Bejeweled Blitz (Mobile), Peggle 2, BookWorm Heroes for iOS and Zuma's Revenge + HD for iOS and PS3, Solitaire Blitz for iOS may be here too but no one has public access to an IPA of it. I will share an IPA of Candy Train in a DM to not promote piracy here. I forgot about A.S.P for iOS which also uses RSB v1.

Edit: A.S.P is the only one that uses RSBV1 aside from Bejeweled Classic v1.0.0

**Comment by LolHacksRule** [comment]
I prob have to still rename the vars but I committed a proper fix for reading v1 RSB. If anything is wrong feel free to reopen the issue.

**Comment by twinstar6980** [comment]
About ResGroupInfo, the flags is a bitset, its first bit represents part1 of rsg compressed with zlib, and the second bit represents part0 of rsg compressed with zlib, so it can have 4 values: 0, 1, 2, 3 (although many Only 1 and 3 appeared in the popcap game, but 0 and 2 can also be loaded normally in the game.
About PTXInfo, the alphaFormat is the scaling ratio. In the Android version of pvz2c, adjusting this value can scale the size of the texture when rendering, but it seems to be invalid in the iPhone version. When ptxInfoTableItemSize==24, there are actually two situations. Some versions of pvz2c first alphaSize and then scale, and some versions first scale and then alphaSize. This is kind of bad, it doesn't seem to be able to determine at runtime.

**Comment by twinstar6980** [comment]
btw, the decoding logic of the ppf file can be found in zuma's c# source code, which can be used to make bt
